/**
 * Brand Icon System
 *
 * Custom pixel-art SVG icons built entirely from rectangles.
 * All icons use a 16x16 viewBox for pixel-perfect rendering.
 *
 * Migration: Switched from Phosphor wrappers to custom pixel icons
 * for consistent geometric aesthetic across the brand.
 */

// Core types
export { PixelIconBase, type PixelIconProps } from './pixel'

// Navigation icons
export {
  IconCaretDown,
  IconCaretLeft,
  IconCaretRight,
  IconCaretUp,
  IconCaretDoubleLeft,
  IconCaretDoubleRight,
  IconArrowRight,
  IconArrowLeft,
  IconArrowDown,
  IconArrowUp,
  IconArrowUpRight,
  IconArrowDownLeft,
  IconRefresh,
  IconUndo,
  IconExternalLink,
  // Aliases
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconChevronUp,
  IconChevronsLeft,
  IconChevronsRight,
} from './pixel'

// Action icons
export {
  IconX,
  IconCheck,
  IconPlus,
  IconMinus,
  IconSearch,
  IconTrash,
  IconEdit,
  IconCopy,
  IconEraser,
  IconDownload,
  IconUpload,
  IconSave,
  IconSend,
  IconMoreHorizontal,
  IconMoreVertical,
  IconLink,
  IconUnlink,
  IconSelectAll,
  IconCommand,
  // Aliases
  IconTrash2,
  IconPencil,
} from './pixel'

// Status icons
export {
  IconCheckCircle,
  IconXCircle,
  IconWarningCircle,
  IconInfo,
  IconQuestion,
  IconWarning,
  IconProhibit,
  IconShieldCheck,
  IconShieldWarning,
  IconClock,
  IconHourglass,
  IconCheckSquare,
  IconSquare,
  IconCircle,
  IconBug,
  IconTrendUp,
  IconFlag,
  // Aliases
  IconCheckCircle2,
  IconAlertCircle,
  IconAlertTriangle,
  IconHelpCircle,
} from './pixel'

// Domain icons
export {
  IconFileText,
  IconFile,
  IconFileCsv,
  IconFileXls,
  IconFilePdf,
  IconFolder,
  IconFolderOpen,
  IconBuildings,
  IconBuilding,
  IconHouse,
  IconTable,
  IconDatabase,
  IconHardDrive,
  IconDollarSign,
  IconMoney,
  IconReceipt,
  IconInvoice,
  IconBank,
  IconCreditCard,
  IconWallet,
  IconCalculator,
  IconChartLine,
  IconChartBar,
  IconChartPie,
  IconCalendar,
  IconCalendarBlank,
  IconTag,
  IconHash,
  IconUser,
  IconUsers,
  IconUserCircle,
  IconBriefcase,
  IconGear,
  IconSliders,
  IconBell,
  IconBellRinging,
  IconEnvelope,
  IconEnvelopeOpen,
  IconChat,
  IconChatDots,
  IconImage,
  IconCamera,
  IconPaperclip,
  IconCloud,
  IconCloudUpload,
  IconCloudDownload,
  IconLock,
  IconUnlock,
  IconKey,
  IconSignIn,
  IconSignOut,
  IconGlobe,
  IconMapPin,
  IconCode,
  IconFileCode,
  IconFilmStrip,
  IconSquaresFour,
  IconGitDiff,
  // Aliases
  IconBuilding2,
  IconTable2,
  IconMail,
  IconMessageCircle,
  IconSettings,
  IconLogIn,
  IconLogOut,
} from './pixel'

// UI icons
export {
  IconLoader,
  IconLoaderStatic,
  IconSpinner,
  IconEye,
  IconEyeOff,
  IconFilter,
  IconSortAsc,
  IconSortDesc,
  IconList,
  IconListBullets,
  IconGrid,
  IconRows,
  IconColumns,
  IconSidebar,
  IconLayout,
  IconSun,
  IconMoon,
  IconDesktop,
  IconLaptop,
  IconMobile,
  IconMaximize,
  IconMinimize,
  IconExpand,
  IconCollapse,
  IconAlignLeft,
  IconAlignCenter,
  IconAlignRight,
  IconText,
  IconTextAa,
  IconZoomIn,
  IconZoomOut,
  IconDropdown,
  IconPlay,
  IconPause,
  IconStop,
  IconSkipForward,
  IconSkipBack,
  IconVolumeOn,
  IconVolumeOff,
  IconPower,
  IconLightning,
  IconZap,
  IconPanelCollapse,
  IconPanelExpand,
  IconDemo,
  IconReal,
  IconSwitch,
  IconDashboard,
  IconReconcile,
  IconReports,
  // Aliases
  IconLoader2,
  IconEyeClosed,
  IconPanelLeft,
} from './pixel'

// AI icons
export {
  IconSparkle,
  IconSparkles,
  IconWand,
  IconRobot,
  IconBrain,
  IconLightbulb,
  IconAtom,
  IconCpu,
  IconCircuitry,
  IconTarget,
  IconCrosshair,
  IconGitBranch,
  IconGitMerge,
  IconPulse,
  IconActivity,
  IconTree,
  IconFlow,
  IconShuffle,
  IconSwap,
  IconStack,
  IconLayers,
} from './pixel'
