/**
 * Pixel Icon System
 *
 * Custom pixel-art SVG icons built entirely from rectangles.
 * All icons use a 16x16 viewBox with rectangle-only composition.
 *
 * Design principles:
 * - Rectangle-only: All shapes are <rect> elements
 * - 16x16 viewBox: Standard grid for all icons
 * - fill="currentColor": Inherits color from context
 * - Opacity for depth: 0.3-0.5 for secondary elements
 */

// Core types and utilities
export { PixelIconBase, type PixelIconProps } from './pixel-core'

// Action icons (X, Check, Plus, Minus, Search, Trash, etc.)
export {
  IconX,
  IconCheck,
  IconPlus,
  IconMinus,
  IconSearch,
  IconTrash,
  IconEdit,
  IconCopy,
  IconEraser,
  IconDownload,
  IconUpload,
  IconSave,
  IconSend,
  IconMoreHorizontal,
  IconMoreVertical,
  IconLink,
  IconUnlink,
  IconSelectAll,
  IconCommand,
  // Aliases
  IconTrash2,
  IconPencil,
} from './pixel-actions'

// Navigation icons (Carets, Arrows)
export {
  IconCaretDown,
  IconCaretUp,
  IconCaretLeft,
  IconCaretRight,
  IconCaretDoubleLeft,
  IconCaretDoubleRight,
  IconArrowRight,
  IconArrowLeft,
  IconArrowDown,
  IconArrowUp,
  IconArrowUpRight,
  IconArrowDownLeft,
  IconRefresh,
  IconUndo,
  IconExternalLink,
  // Aliases
  IconChevronDown,
  IconChevronUp,
  IconChevronLeft,
  IconChevronRight,
  IconChevronsLeft,
  IconChevronsRight,
} from './pixel-navigation'

// Status icons (CheckCircle, XCircle, Warning, Info, etc.)
export {
  IconCheckCircle,
  IconXCircle,
  IconWarningCircle,
  IconInfo,
  IconQuestion,
  IconWarning,
  IconProhibit,
  IconShieldCheck,
  IconShieldWarning,
  IconClock,
  IconHourglass,
  IconCheckSquare,
  IconSquare,
  IconCircle,
  IconBug,
  IconTrendUp,
  IconFlag,
  // Aliases
  IconCheckCircle2,
  IconAlertCircle,
  IconAlertTriangle,
  IconHelpCircle,
} from './pixel-status'

// UI icons (Loader, Eye, Filter, Grid, etc.)
export {
  IconLoader,
  IconLoaderStatic,
  IconSpinner,
  IconEye,
  IconEyeOff,
  IconFilter,
  IconSortAsc,
  IconSortDesc,
  IconList,
  IconListBullets,
  IconGrid,
  IconRows,
  IconColumns,
  IconSidebar,
  IconLayout,
  IconSun,
  IconMoon,
  IconDesktop,
  IconLaptop,
  IconMobile,
  IconMaximize,
  IconMinimize,
  IconExpand,
  IconCollapse,
  IconAlignLeft,
  IconAlignCenter,
  IconAlignRight,
  IconText,
  IconTextAa,
  IconZoomIn,
  IconZoomOut,
  IconDropdown,
  IconPlay,
  IconPause,
  IconStop,
  IconSkipForward,
  IconSkipBack,
  IconVolumeOn,
  IconVolumeOff,
  IconPower,
  IconLightning,
  IconPanelCollapse,
  IconPanelExpand,
  IconDemo,
  IconReal,
  IconSwitch,
  IconDashboard,
  IconReconcile,
  IconReports,
  // Aliases
  IconLoader2,
  IconEyeClosed,
  IconPanelLeft,
  IconZap,
} from './pixel-ui'

// AI icons (Sparkle, Brain, Wand, etc.)
export {
  IconSparkle,
  IconSparkles,
  IconWand,
  IconRobot,
  IconBrain,
  IconLightbulb,
  IconAtom,
  IconCpu,
  IconTarget,
  IconCrosshair,
  IconGitBranch,
  IconGitMerge,
  IconPulse,
  IconTree,
  IconFlow,
  IconShuffle,
  IconSwap,
  IconStack,
  // Aliases
  IconCircuitry,
  IconActivity,
  IconLayers,
} from './pixel-ai'

// Domain icons (File, Folder, Building, User, etc.)
export {
  IconFileText,
  IconFile,
  IconFileCsv,
  IconFileXls,
  IconFilePdf,
  IconFolder,
  IconFolderOpen,
  IconBuildings,
  IconBuilding,
  IconHouse,
  IconTable,
  IconDatabase,
  IconHardDrive,
  IconDollarSign,
  IconMoney,
  IconReceipt,
  IconInvoice,
  IconBank,
  IconCreditCard,
  IconWallet,
  IconCalculator,
  IconChartLine,
  IconChartBar,
  IconChartPie,
  IconCalendar,
  IconCalendarBlank,
  IconTag,
  IconHash,
  IconUser,
  IconUsers,
  IconUserCircle,
  IconBriefcase,
  IconGear,
  IconSliders,
  IconBell,
  IconBellRinging,
  IconEnvelope,
  IconEnvelopeOpen,
  IconChat,
  IconChatDots,
  IconImage,
  IconCamera,
  IconPaperclip,
  IconCloud,
  IconCloudUpload,
  IconCloudDownload,
  IconLock,
  IconUnlock,
  IconKey,
  IconSignIn,
  IconSignOut,
  IconGlobe,
  IconMapPin,
  IconCode,
  IconFileCode,
  IconFilmStrip,
  IconSquaresFour,
  IconGitDiff,
  // Aliases
  IconBuilding2,
  IconTable2,
  IconMail,
  IconMessageCircle,
  IconSettings,
  IconLogIn,
  IconLogOut,
} from './pixel-domain'
